---
- hosts: all
  tasks:
  - name: change grub file
    lineinfile:
      state: present
      dest: /etc/default/grub
      backrefs: yes
      regexp: ^(GRUB_CMDLINE_LINUX=(?!.* {{item}})\"[^\"]+)(\".*)
      line: '\1 {{item}}=0\2'
    loop:
      - "biosdevname"
      - "net.ifnames"
            
  - name: Write grub configuration file
    command: grub2-mkconfig
      
... 